### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by rknightuk** [justdeleteme/justdelete.me#2]
- [x] Add extra info tooltip
- [x] Update readme to include submission guidelines
- [x] Write blog post
- [x] Confirm Medium delete
- [x] Favicon
- [x] iOS icon
- [x] GoSquared
- [x] Google Web Master
